package org.esaude.dmt.helper;

public enum ValidationStatuses {
	RIGHT_TO_LEFT_DATATYPE_COMPATIBILITY,
	RIGHT_TO_LEFT_DATATYPE_INCOMPATIBILITY,
	LEFT_TO_RIGT_DATATYPE_COMPATIBILITY,
	LEFT_TO_RIGT_DATATYPE_INCOMPATIBILITY,
	LEFT_TO_RIGHT_SIZE_INCOMPATIBILITY

}
